name: Main

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  compile:
    runs-on: windows-latest
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.16.x'

    - name: Use cmake
      run: cmake --version

    - name: Use ccmake
      run: ccmake --version

    - name: Use make
      run: make --version

    - name: Checkout mapbox/protozero
      uses: actions/checkout@v4
      with:
        repository: mapbox/protozero

    - name: Checkout osmcode/libosmium
      uses: actions/checkout@v4
      with:
        repository: osmcode/libosmium

    - name: Checkout osmcode/osmium-tool
      uses: actions/checkout@v4
      with:
        repository: osmcode/osmium-tool

    - name: Make
      run: |
        cd osmium-tool
        mkdir build
        cd build
        cmake ..
        ccmake .
        make
        ls src\
        ls src\Release\
